### ISSUE TITLE
Install problem - libshiboken-python2.7.1.1 not found

### ISSUE THREAD

**Issue by thundergolfer** [cbrew/Insults#1]
After running the `conda install` command, I was unable to run `insults.py`. I got the following error:

```
from PySide import QtCore, QtGui, __version__, __version_info__
ImportError: libshiboken-python2.7.so.1.1: cannot open shared object file: No such file or directory
```

I am working on finding the problem, but just wanted to post that the `conda` solution didn't work smoothly.

**Comment by thundergolfer** [comment]
running `conda install pyside` updated PySide and fixed the problem.

**Comment by cbrew** [comment]
Thankyou.
